### ISSUE TITLE
Catalog is 2MRS got error

### ISSUE THREAD

**Issue by parkma99** [skyportal/gwemopt#145]
When I run command `python -m gwemopt  --event S230609u --catalog 2MRS`, I got error , message is below:
```shell
Found voevent S230609u-5-Update.xml
Latest skymap URL: https://gracedb.ligo.org/api/superevents/S230609u/files/Bilby.multiorder.fits,0
File /home/ma/Data/gwemopt/skymaps/S230609u_5_Bilby.multiorder.fits,0 already exists. Using this.
natural_nside = 256
nside = 256
Output directory: /home/ma/Data/gwemopt/S230609u_5_Bilby.multiorder/ATLAS
Loading skymap...
Generating catalog...
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/home/ma/code/gwemopt/gwemopt/__main__.py", line 55, in <module>
    run(sys.argv[1:])
  File "/home/ma/code/gwemopt/gwemopt/run.py", line 59, in run
    map_struct, catalog_struct = get_catalog(params, map_struct)
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ma/code/gwemopt/gwemopt/catalogs/get.py", line 46, in get_catalog
    cat_df = cat.get_catalog()
             ^^^^^^^^^^^^^^^^^
  File "/home/ma/code/gwemopt/gwemopt/catalogs/base_catalog.py", line 35, in get_catalog
    self.download_catalog()
  File "/home/ma/code/gwemopt/gwemopt/catalogs/twomrs.py", line 18, in download_catalog
    cat["z"] = (u.Quantity(cat["cz"]) / c.c).to(u.dimensionless_unscaled)
                           ~~~^^^^^^
  File "/home/ma/miniconda3/envs/gwemopt/lib/python3.11/site-packages/astroquery/utils/commons.py", line 253, in __getitem__
    raise TypeError("TableLists can only be indexed with the "
TypeError: TableLists can only be indexed with the named keys and integers.
```

**Comment by mcoughlin** [comment]
@parkma99 Please try again. Feel free to reopen if you run into the same issue.
